name: PHPUnit

on:
  push:
    branches: [ main, master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
  uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: mbstring, pdo, pdo_sqlite, xml
          ini-values: post_max_size=256M, memory_limit=2G

      - name: Validate composer
        run: composer --version

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env || true
          php artisan key:generate --ansi || true

      - name: Create SQLite database file
        run: |
          mkdir -p database || true
          touch database/database.sqlite || true

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always --testdox
